"""removed another test field

Revision ID: 14d8c5baf427
Revises: dae4f21aa099
Create Date: 2026-02-09 17:33:25.129357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14d8c5baf427'
down_revision: Union[str, Sequence[str], None] = 'dae4f21aa099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name_test', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
