"""fixed fk relationship

Revision ID: 15e073ba14d4
Revises: fdaf8b84b9a1
Create Date: 2026-02-13 17:31:30.376759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15e073ba14d4'
down_revision: Union[str, Sequence[str], None] = 'fdaf8b84b9a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('financial_overview_asset_symbol_fkey'), 'financial_overview', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('financial_overview_asset_symbol_fkey'), 'financial_overview', 'asset', ['asset_symbol'], ['symbol'], ondelete='CASCADE')
    # ### end Alembic commands ###
