"""changed field name for ah confidence

Revision ID: 2a4ff6454a4b
Revises: 9d1d120c9207
Create Date: 2026-02-27 14:02:16.043643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a4ff6454a4b'
down_revision: Union[str, Sequence[str], None] = '9d1d120c9207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_event_history', sa.Column('confidence', sa.String(length=256), nullable=False))
    op.drop_column('alert_event_history', 'reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_event_history', sa.Column('reason', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('alert_event_history', 'confidence')
    # ### end Alembic commands ###
