"""add trade fields to alert_event_history

Revision ID: 55535c5ef712
Revises: 7342850a6c9d
Create Date: 2026-03-23 16:27:39.572604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55535c5ef712'
down_revision: Union[str, Sequence[str], None] = '7342850a6c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_event_history', sa.Column('symbol', sa.String(length=16), nullable=True))
    op.add_column('alert_event_history', sa.Column('price', sa.Double(precision=53), nullable=True))
    op.add_column('alert_event_history', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('alert_event_history', sa.Column('exchange', sa.String(length=8), nullable=True))
    op.add_column('alert_event_history', sa.Column('trade_id', sa.Integer(), nullable=True))
    op.add_column('alert_event_history', sa.Column('conditions', sa.String(length=256), nullable=True))
    op.add_column('alert_event_history', sa.Column('tape', sa.String(length=4), nullable=True))
    op.add_column('alert_event_history', sa.Column('trade_timestamp', sa.DateTime(), nullable=True))
    op.drop_column('alert_event_history', 'trade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_event_history', sa.Column('trade', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('alert_event_history', 'trade_timestamp')
    op.drop_column('alert_event_history', 'tape')
    op.drop_column('alert_event_history', 'conditions')
    op.drop_column('alert_event_history', 'trade_id')
    op.drop_column('alert_event_history', 'exchange')
    op.drop_column('alert_event_history', 'size')
    op.drop_column('alert_event_history', 'price')
    op.drop_column('alert_event_history', 'symbol')
    # ### end Alembic commands ###
