"""fixed cascading delete for alert and alert history

Revision ID: 7342850a6c9d
Revises: 2a4ff6454a4b
Create Date: 2026-02-27 15:49:45.961612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7342850a6c9d'
down_revision: Union[str, Sequence[str], None] = '2a4ff6454a4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
