"""baseline

Revision ID: ecf8b0abf9de
Revises: 
Create Date: 2026-04-09 01:23:52.476505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecf8b0abf9de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert', sa.Column('alert_type_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('alert_user_id_fkey'), 'alert', type_='foreignkey')
    op.create_foreign_key(None, 'alert', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'alert', 'alert_type', ['alert_type_id'], ['id'])
    op.drop_column('alert', 'created_at')
    op.drop_column('alert', 'alert_type')
    op.add_column('alert_event_history', sa.Column('confidence', sa.String(length=256), nullable=False))
    op.add_column('alert_event_history', sa.Column('symbol', sa.String(length=16), nullable=True))
    op.add_column('alert_event_history', sa.Column('price', sa.Double(precision=53), nullable=True))
    op.add_column('alert_event_history', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('alert_event_history', sa.Column('exchange', sa.String(length=8), nullable=True))
    op.add_column('alert_event_history', sa.Column('trade_id', sa.Integer(), nullable=True))
    op.add_column('alert_event_history', sa.Column('conditions', sa.String(length=256), nullable=True))
    op.add_column('alert_event_history', sa.Column('tape', sa.String(length=4), nullable=True))
    op.add_column('alert_event_history', sa.Column('trade_timestamp', sa.DateTime(), nullable=True))
    op.alter_column('asset', 'symbol',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_constraint(op.f('asset_symbol_key'), 'asset', type_='unique')
    op.create_unique_constraint('asset_symbol_unique', 'asset', ['symbol'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('asset_symbol_unique', 'asset', type_='unique')
    op.create_unique_constraint(op.f('asset_symbol_key'), 'asset', ['symbol'], postgresql_nulls_not_distinct=False)
    op.alter_column('asset', 'symbol',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.drop_column('alert_event_history', 'trade_timestamp')
    op.drop_column('alert_event_history', 'tape')
    op.drop_column('alert_event_history', 'conditions')
    op.drop_column('alert_event_history', 'trade_id')
    op.drop_column('alert_event_history', 'exchange')
    op.drop_column('alert_event_history', 'size')
    op.drop_column('alert_event_history', 'price')
    op.drop_column('alert_event_history', 'symbol')
    op.drop_column('alert_event_history', 'confidence')
    op.add_column('alert', sa.Column('alert_type', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.add_column('alert', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'alert', type_='foreignkey')
    op.drop_constraint(None, 'alert', type_='foreignkey')
    op.create_foreign_key(op.f('alert_user_id_fkey'), 'alert', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('alert', 'alert_type_id')
    # ### end Alembic commands ###
