"""added field to financial overview

Revision ID: fdaf8b84b9a1
Revises: ebe7a10822c2
Create Date: 2026-02-13 16:48:19.624838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdaf8b84b9a1'
down_revision: Union[str, Sequence[str], None] = 'ebe7a10822c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_overview', sa.Column('total_revenue', sa.Numeric(precision=20, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_overview', 'total_revenue')
    # ### end Alembic commands ###
